function choice = SelectBenchmark

    d = dialog('Position',[300 300 250 150],'Name','Select Data Set');
    txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 80 210 40],...
           'String','Select Benchmark');
       
    popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 70 150 25],...
           'String',{'Sphere';'Cigar';'Ellipse';'Rosenbrock';'Griewangk'},...
           'Callback',@popup_callback);
       
    btn = uicontrol('Parent',d,...
           'Position',[89 20 70 25],...
           'String','Select',...
           'Callback','delete(gcf)');
       
    choice = 'Ackley';
 
    uiwait(d);
   
       function popup_callback(popup,callbackdata)
          idx = popup.Value;
          popup_items = popup.String;
          choice = char(popup_items(idx,:));
       end
end